# Generated by Django 2.1.1 on 2018-09-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vedio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='actor_work_name',
        ),
        migrations.RemoveField(
            model_name='director',
            name='directors_work_name',
        ),
    ]
