# Generated by Django 2.1.1 on 2018-09-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedio', '0002_auto_20180926_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='base_city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='country',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='nation',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='base_city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='country',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='director',
            name='nation',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='sex',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='resources',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='type',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
